# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=120)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=120)),
                ('contact', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
