# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-28 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='comment',
            field=models.TextField(default='neck pain'),
            preserve_default=False,
        ),
    ]
