# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-30 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20181230_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='desctiption',
            new_name='description',
        ),
    ]
