# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-16 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0005_auto_20181231_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_by',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_level',
        ),
        migrations.AddField(
            model_name='labtest',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labtest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 16, 6, 57, 3, 365378, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_sampled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='result',
            field=models.CharField(default='pending', max_length=120),
        ),
    ]
