# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-16 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0006_auto_20190116_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 16, 7, 39, 0, 70956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='result',
            field=models.CharField(default='pending', max_length=120, null=True),
        ),
    ]
