# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-31 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0008_auto_20181231_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 31, 7, 39, 48, 874345, tzinfo=utc)),
        ),
    ]
