# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-31 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0009_auto_20181231_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_date',
        ),
    ]
