# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-22 04:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0014_auto_20190120_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 22, 4, 23, 42, 196325, tzinfo=utc)),
        ),
    ]
