# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-29 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0023_auto_20190129_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 29, 6, 25, 7, 708234, tzinfo=utc)),
        ),
    ]
