# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-11 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0024_auto_20190129_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 11, 8, 17, 53, 113332, tzinfo=utc)),
        ),
    ]
