# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-13 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_auto_20181230_1309'),
        ('doctors', '0004_auto_20181228_1325'),
        ('medicals', '0002_auto_20181230_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=120)),
                ('comment', models.TextField()),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime(2019, 1, 13, 9, 33, 48, 612247, tzinfo=utc))),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('refered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicals.Medical')),
            ],
        ),
    ]
