# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-31 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicals', '0002_auto_20181230_1233'),
        ('doctors', '0004_auto_20181228_1325'),
        ('patients', '0004_auto_20181230_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=120)),
                ('comment', models.TextField()),
                ('follow_up_date', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('provided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicals.Medical')),
                ('refered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
        ),
    ]
