# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-31 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
