# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-31 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_auto_20181231_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='provided_by',
        ),
    ]
