# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-22 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20190122_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 22, 4, 25, 15, 729682, tzinfo=utc)),
        ),
    ]
