# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-31 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_remove_medicine_provided_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='refered_by',
            new_name='doctor',
        ),
    ]
