# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-22 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20190122_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 22, 4, 31, 8, 924809, tzinfo=utc)),
        ),
    ]
