# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-22 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_auto_20190122_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 22, 12, 38, 37, 934708, tzinfo=utc)),
        ),
    ]
