# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-28 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20181228_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor',
            new_name='user',
        ),
    ]
