# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-04 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicals', '0002_auto_20181230_1233'),
        ('patients', '0004_auto_20181230_1309'),
        ('doctors', '0004_auto_20181228_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=120)),
                ('comment', models.TextField()),
                ('is_supplied', models.BooleanField(default=False)),
                ('total_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicals.Medical')),
            ],
        ),
    ]
