# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-04 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalmedicine',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 9, 56, 25, 322129, tzinfo=utc)),
        ),
    ]
