# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-29 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorist',
            name='joined_date',
        ),
    ]
