# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(default=0)),
                ('permanent_address', models.CharField(max_length=120)),
                ('temporary_address', models.CharField(max_length=120)),
                ('qualification', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='profile')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
